# Generated by Django 5.1.4 on 2024-12-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
